


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."api_products" (
    "api_product_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "api_name" "text" NOT NULL
);


ALTER TABLE "public"."api_products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."api_usage" (
    "api_usage_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "api_product_id" "uuid" NOT NULL,
    "used_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."api_usage" OWNER TO "postgres";


ALTER TABLE "public"."api_usage" ALTER COLUMN "api_usage_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."api_usage_api_usage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."payment_history" (
    "amount_paid" numeric NOT NULL,
    "paid_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "period_start" "date" DEFAULT CURRENT_DATE NOT NULL,
    "payment_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "subscription_id" "uuid",
    "card_last4" "text"
);


ALTER TABLE "public"."payment_history" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."plan_api_limits" (
    "plan_id" "uuid" NOT NULL,
    "api_product_id" "uuid" NOT NULL,
    "monthly_limit" bigint NOT NULL
);


ALTER TABLE "public"."plan_api_limits" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."plans" (
    "plan_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "plan_name" "text" NOT NULL,
    "price_per_month" numeric NOT NULL,
    "description" "text" NOT NULL,
    "is_active" boolean NOT NULL
);


ALTER TABLE "public"."plans" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "subscription_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "plan_id" "uuid",
    "started_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "ended_at" timestamp with time zone,
    "pending_plan_id" "uuid"
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "username" "public"."citext" NOT NULL,
    "hash" "text" NOT NULL,
    "email" "text" NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."api_products"
    ADD CONSTRAINT "api_products_api_name_key" UNIQUE ("api_name");



ALTER TABLE ONLY "public"."api_products"
    ADD CONSTRAINT "api_products_pkey" PRIMARY KEY ("api_product_id");



ALTER TABLE ONLY "public"."api_usage"
    ADD CONSTRAINT "api_usage_pkey" PRIMARY KEY ("api_usage_id");



ALTER TABLE ONLY "public"."payment_history"
    ADD CONSTRAINT "payment_history_pkey" PRIMARY KEY ("payment_id");



ALTER TABLE ONLY "public"."payment_history"
    ADD CONSTRAINT "payment_once_per_period" UNIQUE ("subscription_id", "period_start");



ALTER TABLE ONLY "public"."plan_api_limits"
    ADD CONSTRAINT "plan_api_limits_pkey" PRIMARY KEY ("plan_id", "api_product_id");



ALTER TABLE ONLY "public"."plans"
    ADD CONSTRAINT "plans_pkey" PRIMARY KEY ("plan_id");



ALTER TABLE ONLY "public"."plans"
    ADD CONSTRAINT "plans_plan_name_key" UNIQUE ("plan_name");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("subscription_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



-- Pagination index for the usage log.
CREATE INDEX IF NOT EXISTS "api_usage_user_used_at_idx"
    ON "public"."api_usage" ("user_id", "used_at" DESC);




CREATE UNIQUE INDEX "one_active_subscription_per_user" ON "public"."subscriptions" USING "btree" ("user_id") WHERE ("ended_at" IS NULL);



ALTER TABLE ONLY "public"."api_usage"
    ADD CONSTRAINT "api_usage_api_product_id_fkey" FOREIGN KEY ("api_product_id") REFERENCES "public"."api_products"("api_product_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."api_usage"
    ADD CONSTRAINT "api_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."payment_history"
    ADD CONSTRAINT "payment_history_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("subscription_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."plan_api_limits"
    ADD CONSTRAINT "plan_api_limits_api_product_id_fkey" FOREIGN KEY ("api_product_id") REFERENCES "public"."api_products"("api_product_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."plan_api_limits"
    ADD CONSTRAINT "plan_api_limits_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("plan_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pending_plan_id_fkey" FOREIGN KEY ("pending_plan_id") REFERENCES "public"."plans"("plan_id") ON UPDATE NO ACTION ON DELETE SET NULL;



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("plan_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."api_products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."api_usage" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."payment_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."plan_api_limits" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."plans" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;