-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

CREATE EXTENSION citext WITH SCHEMA public;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE TABLE public.api_products (
  api_product_id uuid DEFAULT gen_random_uuid() NOT NULL,
  api_name       text NOT NULL
);

ALTER TABLE public.api_products
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.api_products
  ADD CONSTRAINT api_products_api_name_key UNIQUE (api_name);

ALTER TABLE public.api_products
  ADD CONSTRAINT api_products_pkey PRIMARY KEY (api_product_id);

GRANT ALL ON public.api_products TO anon;

GRANT ALL ON public.api_products TO authenticated;

GRANT ALL ON public.api_products TO service_role;

CREATE TABLE public.api_usage (
  api_usage_id   bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id        uuid                     NOT NULL,
  api_product_id uuid                     NOT NULL,
  used_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.api_usage
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.api_usage
  ADD CONSTRAINT api_usage_api_product_id_fkey FOREIGN KEY (api_product_id) REFERENCES public.api_products(api_product_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.api_usage
  ADD CONSTRAINT api_usage_pkey PRIMARY KEY (api_usage_id);

GRANT ALL ON public.api_usage TO anon;

GRANT ALL ON public.api_usage TO authenticated;

GRANT ALL ON public.api_usage TO service_role;

CREATE INDEX api_usage_user_id_idx ON public.api_usage (user_id, api_usage_id DESC);

CREATE TABLE public.payment_history (
  amount_paid     numeric                  NOT NULL,
  paid_at         timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  period_start    date                     DEFAULT CURRENT_DATE NOT NULL,
  payment_id      uuid                     DEFAULT gen_random_uuid() NOT NULL,
  subscription_id uuid,
  card_last4      text
);

ALTER TABLE public.payment_history
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.payment_history
  ADD CONSTRAINT payment_history_pkey PRIMARY KEY (payment_id);

ALTER TABLE public.payment_history
  ADD CONSTRAINT payment_once_per_period UNIQUE (subscription_id, period_start);

GRANT ALL ON public.payment_history TO anon;

GRANT ALL ON public.payment_history TO authenticated;

GRANT ALL ON public.payment_history TO service_role;

CREATE TABLE public.plan_api_limits (
  plan_id        uuid   NOT NULL,
  api_product_id uuid   NOT NULL,
  monthly_limit  bigint NOT NULL
);

ALTER TABLE public.plan_api_limits
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.plan_api_limits
  ADD CONSTRAINT plan_api_limits_api_product_id_fkey FOREIGN KEY (api_product_id) REFERENCES public.api_products(api_product_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.plan_api_limits
  ADD CONSTRAINT plan_api_limits_pkey PRIMARY KEY (plan_id, api_product_id);

GRANT ALL ON public.plan_api_limits TO anon;

GRANT ALL ON public.plan_api_limits TO authenticated;

GRANT ALL ON public.plan_api_limits TO service_role;

CREATE TABLE public.plans (
  plan_id         uuid    DEFAULT gen_random_uuid() NOT NULL,
  plan_name       text    NOT NULL,
  price_per_month numeric NOT NULL,
  description     text    NOT NULL,
  is_active       boolean NOT NULL
);

ALTER TABLE public.plans
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.plans
  ADD CONSTRAINT plans_pkey PRIMARY KEY (plan_id);

ALTER TABLE public.plan_api_limits
  ADD CONSTRAINT plan_api_limits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.plans
  ADD CONSTRAINT plans_plan_name_key UNIQUE (plan_name);

GRANT ALL ON public.plans TO anon;

GRANT ALL ON public.plans TO authenticated;

GRANT ALL ON public.plans TO service_role;

CREATE TABLE public.subscriptions (
  subscription_id uuid                     DEFAULT gen_random_uuid() NOT NULL,
  user_id         uuid                     NOT NULL,
  plan_id         uuid,
  started_at      timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  ended_at        timestamp with time zone
);

ALTER TABLE public.subscriptions
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id);

ALTER TABLE public.payment_history
  ADD CONSTRAINT payment_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(subscription_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON UPDATE CASCADE ON DELETE CASCADE;

GRANT ALL ON public.subscriptions TO anon;

GRANT ALL ON public.subscriptions TO authenticated;

GRANT ALL ON public.subscriptions TO service_role;

CREATE UNIQUE INDEX one_active_subscription_per_user ON public.subscriptions (user_id)
  WHERE ended_at IS NULL;

CREATE TABLE public.users (
  user_id    uuid                     DEFAULT gen_random_uuid() NOT NULL,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  username   public.citext            NOT NULL,
  hash       text                     NOT NULL,
  email      text                     NOT NULL
);

ALTER TABLE public.users
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users
  ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE public.users
  ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE public.api_usage
  ADD CONSTRAINT api_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.users
  ADD CONSTRAINT users_username_key UNIQUE (username);

GRANT ALL ON public.users TO anon;

GRANT ALL ON public.users TO authenticated;

GRANT ALL ON public.users TO service_role;
